baseURL = "https://www.clementfleury.me"
title = "Clément Fleury"
theme = "coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
disqusShortname = ""
canonifyURLs = true
themesDir = "themes"

[params]
author = "Clément Fleury"
description = "Clément Fleury's personal website"
keywords = "blog,developer,personal,data,science,artificial intelligence"
avatarURL = "images/avatar.jpg"
gravatar = "clement.fleury@pm.me"
favicon_32 = "/images/favicon-32x32.png"
favicon_16 = "/images/favicon-16x16.png"
footerContent = ""
hideFooter = true
hideCredits = true
hideCopyright = true
since = 2_021
enableTwemoji = true
colorScheme = "auto"
hideColorSchemeToggle = false
customCSS = [ ]
customSCSS = [ ]
customJS = [ ]

  [[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/clementfleury/"

  [[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/f13uryc"

  [[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 3
  url = "https://github.com/fleuryc/"

  [[params.social]]
  name = "Stack Overflow"
  icon = "fa fa-stack-overflow fa-2x"
  weight = 4
  url = "https://stackoverflow.com/users/1415232/fleuryc"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"
